package airline.reservation.system;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Michael
 */

//import java.sql.*;
import airlineDB.DatabaseConnection;
import javax.swing.JOptionPane;
import java.awt.event.*;
import java.awt.*;
import javax.swing.*;

public class Login extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form Login
     */
    String userNameInitVal="UserName";
    String pswdInitVal="Password";
    static boolean isLoggedIn=false;
    static String logInFrom=null;
   public static int Cust_Id=0;
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        setOpacity(0.0f);
        Thread t1=new Thread(this);
        t1.start();
        setVisible(true);
    }
     
    public void run(){
        try{
            for(float i=0.0f;i<=0.92f;i+=0.01){
                setOpacity(i);
                Thread.sleep(5);
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLogo = new javax.swing.JPanel();
        jlpLogo = new javax.swing.JLayeredPane();
        lblLogo = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        pnlLogin = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblUserNameIcon = new javax.swing.JLabel();
        tfUserName = new javax.swing.JTextField();
        pfPassword = new javax.swing.JPasswordField();
        lblPasswordIcon = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        lblprelink = new javax.swing.JLabel();
        lbllink = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        jspUserName = new javax.swing.JSeparator();
        jspPassword = new javax.swing.JSeparator();
        lblUserNameError = new javax.swing.JLabel();
        lblPasswordError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setOpacity(0.9f);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlLogo.setBackground(new java.awt.Color(51, 51, 51));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airline/reservation/system/airplane white.png"))); // NOI18N

        lblName.setFont(new java.awt.Font("Segoe Print", 0, 48)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("SkyCab");

        jlpLogo.setLayer(lblLogo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpLogo.setLayer(lblName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpLogoLayout = new javax.swing.GroupLayout(jlpLogo);
        jlpLogo.setLayout(jlpLogoLayout);
        jlpLogoLayout.setHorizontalGroup(
            jlpLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpLogoLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jlpLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpLogoLayout.createSequentialGroup()
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpLogoLayout.createSequentialGroup()
                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
        );
        jlpLogoLayout.setVerticalGroup(
            jlpLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpLogoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );

        javax.swing.GroupLayout pnlLogoLayout = new javax.swing.GroupLayout(pnlLogo);
        pnlLogo.setLayout(pnlLogoLayout);
        pnlLogoLayout.setHorizontalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addComponent(jlpLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlLogoLayout.setVerticalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlpLogo)
        );

        pnlLogin.setBackground(new java.awt.Color(255, 255, 255));
        pnlLogin.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitle.setText("SIGN IN");

        lblUserNameIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airline/reservation/system/username-black (Custom).png"))); // NOI18N

        tfUserName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfUserName.setText("UserName");
        tfUserName.setBorder(null);
        tfUserName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfUserNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfUserNameFocusLost(evt);
            }
        });

        pfPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pfPassword.setText("Password");
        pfPassword.setBorder(null);
        pfPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pfPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pfPasswordFocusLost(evt);
            }
        });

        lblPasswordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airline/reservation/system/password-icon black (Custom).png"))); // NOI18N

        btnLogin.setBackground(new java.awt.Color(51, 102, 255));
        btnLogin.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Sign In");
        btnLogin.setBorder(null);
        btnLogin.setContentAreaFilled(false);
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.setOpaque(true);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblprelink.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblprelink.setText("Don't have an Account?");

        lbllink.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbllink.setForeground(new java.awt.Color(51, 102, 255));
        lbllink.setText("<html><u>Create one Now</u></html>");
        lbllink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbllink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbllinkMouseClicked(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnCancel.setText("[ X ]");
        btnCancel.setBorder(null);
        btnCancel.setBorderPainted(false);
        btnCancel.setContentAreaFilled(false);
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jspUserName.setOpaque(true);

        jspPassword.setOpaque(true);

        lblUserNameError.setForeground(new java.awt.Color(255, 0, 0));

        lblPasswordError.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jspPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                            .addComponent(jspUserName)
                            .addGroup(pnlLoginLayout.createSequentialGroup()
                                .addComponent(lblPasswordIcon)
                                .addGap(18, 18, 18)
                                .addComponent(pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlLoginLayout.createSequentialGroup()
                                .addComponent(lblUserNameIcon)
                                .addGap(18, 18, 18)
                                .addComponent(tfUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblprelink)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbllink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginLayout.createSequentialGroup()
                        .addComponent(lblUserNameError)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginLayout.createSequentialGroup()
                        .addComponent(lblPasswordError)
                        .addGap(64, 64, 64))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginLayout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addGap(120, 120, 120))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginLayout.createSequentialGroup()
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101))))
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addComponent(btnCancel)
                .addGap(16, 16, 16)
                .addComponent(lblTitle)
                .addGap(43, 43, 43)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblUserNameIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUserNameError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPasswordIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pfPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPasswordError)
                .addGap(23, 23, 23)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbllink, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblprelink))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        pfPassword.setEchoChar((char)0);
    }//GEN-LAST:event_formWindowOpened

    private void pfPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfPasswordFocusGained
        // TODO add your handling code here:
        if(String.valueOf(pfPassword.getPassword()).equals(pswdInitVal)){
            pfPassword.setText("");
            pfPassword.setEchoChar('\u25cf');
        }
    }//GEN-LAST:event_pfPasswordFocusGained

    private void pfPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfPasswordFocusLost
        // TODO add your handling code here:
        if(pfPassword.getPassword().length==0){
            pfPassword.setEchoChar((char)0);
            pfPassword.setText(pswdInitVal);
        }
        
        if(pfPassword.getPassword().length==0 || String.valueOf(pfPassword.getPassword()).equals(pswdInitVal)){
            lblPasswordError.setText("Enter your Password");
        }
        else{
            lblPasswordError.setText("");
        }
            
    }//GEN-LAST:event_pfPasswordFocusLost

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        if(tfUserName.getText().equals(userNameInitVal)){
            jspUserName.setBackground(Color.red);
            lblUserNameError.setText("Enter your UserName");
        }
        
        if(String.valueOf(pfPassword.getPassword()).equals(pswdInitVal)){
            jspUserName.setBackground(Color.red);
            lblPasswordError.setText("Enter your Password");
        }
        
        if(!(tfUserName.getText().equals(userNameInitVal) || String.valueOf(pfPassword.getPassword()).equals(pswdInitVal))){
            try{
                boolean logIn=new DatabaseConnection().logIn(tfUserName.getText(),String.valueOf(pfPassword.getPassword()));
                if(logIn){
                    isLoggedIn=true;
                    if(logInFrom.equals("search")){
                       // System.out.println(Cust_Id);
                        new Search();
                        dispose();
                    }
                    if(logInFrom.equals("book")){
                        new Booking(Search.sum);
                        dispose();
                    }
                    
                }
                else{
                    JOptionPane.showMessageDialog(this,"Invalid UserName or Password","LogIn",JOptionPane.ERROR_MESSAGE);
                }
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(this,ex.toString(),"Exception",JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void tfUserNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUserNameFocusGained
        // TODO add your handling code here:
        if(tfUserName.getText().equals(userNameInitVal)){
            tfUserName.setText("");
        }
    }//GEN-LAST:event_tfUserNameFocusGained

    private void tfUserNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUserNameFocusLost
        // TODO add your handling code here:
        if(tfUserName.getText().length()==0){
            tfUserName.setText(userNameInitVal);
        }
        if(tfUserName.getText().length()==0 || tfUserName.getText().equals(userNameInitVal)){
            lblUserNameError.setText("Enter your UserName");
        }
        else{
            lblUserNameError.setText("");
        }
            
    }//GEN-LAST:event_tfUserNameFocusLost

    private void lbllinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllinkMouseClicked
        // TODO add your handling code here:
        new Registration();
        dispose();
    }//GEN-LAST:event_lbllinkMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLayeredPane jlpLogo;
    private javax.swing.JSeparator jspPassword;
    private javax.swing.JSeparator jspUserName;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPasswordError;
    private javax.swing.JLabel lblPasswordIcon;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUserNameError;
    private javax.swing.JLabel lblUserNameIcon;
    private javax.swing.JLabel lbllink;
    private javax.swing.JLabel lblprelink;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlLogo;
    private javax.swing.JTextField tfUserName;
    // End of variables declaration//GEN-END:variables
}
