package airline.reservation.system;

import com.sun.glass.events.KeyEvent;
import java.awt.Toolkit;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SAGAR KADAM
 */
 import javax.swing.*;
import javax.swing.text.*;
import java.awt.Color;
import airlineDB.DatabaseConnection;
public class Payment extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form payment
     */
   boolean isCardNoValid=false,isCardNameValid=false,isCVVNoValid=false;
    public Payment() {
        initComponents();
        pnlTitle.setBackground(new Color(0,0,0,210));
       ((AbstractDocument)tfCardNo.getDocument()).setDocumentFilter(new NumberDocumentFilter());
       ((AbstractDocument)pfCVV.getDocument()).setDocumentFilter(new NumberDocumentFilter());
       pfCVV.setEchoChar('\u25cf');
       ((AbstractDocument)tfCardName.getDocument()).setDocumentFilter(new CharDocumentFilter());
       ((AbstractDocument)tfIssueNo.getDocument()).setDocumentFilter(new NumberDocumentFilter());
       tfAmt.setEditable(false);
       tfAmt.setText(Integer.toString(FlightPopUp.amt)+" \u20B9");
       setLocationRelativeTo(null);
       setOpacity(0.0f);
       Thread t1=new Thread(this);
       t1.start();
       setVisible(true);
       
    }
    
     public void run(){
        try{
            for(float i=0.0f;i<=0.92f;i+=0.01){
                setOpacity(i);
                Thread.sleep(5);
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPay = new javax.swing.JPanel();
        lblCardNo = new javax.swing.JLabel();
        tfCardNo = new javax.swing.JTextField();
        lblCardName = new javax.swing.JLabel();
        tfCardName = new javax.swing.JTextField();
        lblCvvNo = new javax.swing.JLabel();
        tfIssueNo = new javax.swing.JTextField();
        lblIssueNo = new javax.swing.JLabel();
        lblExpiry = new javax.swing.JLabel();
        chExpiryYr = new javax.swing.JComboBox();
        cbExpiryDate = new javax.swing.JComboBox();
        lblValid = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnPay = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnlTitle = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pfCVV = new javax.swing.JPasswordField();
        lblCardNoError = new javax.swing.JLabel();
        lblCardNameError = new javax.swing.JLabel();
        lblCVVNoError = new javax.swing.JLabel();
        tfAmt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setOpacity(1.0f);

        pnlPay.setBackground(new java.awt.Color(255, 255, 255));
        pnlPay.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N

        lblCardNo.setBackground(new java.awt.Color(255, 255, 255));
        lblCardNo.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        lblCardNo.setText("Card Number");

        tfCardNo.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        tfCardNo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        tfCardNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfCardNoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCardNoFocusLost(evt);
            }
        });
        tfCardNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCardNoActionPerformed(evt);
            }
        });
        tfCardNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfCardNoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfCardNoKeyTyped(evt);
            }
        });

        lblCardName.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        lblCardName.setText("Name on Card");

        tfCardName.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        tfCardName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        tfCardName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCardNameFocusLost(evt);
            }
        });

        lblCvvNo.setBackground(new java.awt.Color(255, 255, 255));
        lblCvvNo.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        lblCvvNo.setText("CVV Number");

        tfIssueNo.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        tfIssueNo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        lblIssueNo.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        lblIssueNo.setText("Issue Number");

        lblExpiry.setBackground(new java.awt.Color(255, 255, 255));
        lblExpiry.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        lblExpiry.setText("Expiry Date");

        chExpiryYr.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        chExpiryYr.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));

        cbExpiryDate.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        cbExpiryDate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        lblValid.setBackground(new java.awt.Color(255, 255, 255));
        lblValid.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        lblValid.setText("Amount");

        lbl1.setForeground(new java.awt.Color(255, 0, 51));
        lbl1.setText("*");

        lbl2.setForeground(new java.awt.Color(255, 0, 51));
        lbl2.setText("*");

        lbl3.setForeground(new java.awt.Color(255, 0, 51));
        lbl3.setText("*");

        lbl4.setForeground(new java.awt.Color(255, 0, 51));
        lbl4.setText("*");

        btnPay.setBackground(new java.awt.Color(51, 102, 255));
        btnPay.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        btnPay.setForeground(new java.awt.Color(255, 255, 255));
        btnPay.setText("Pay");
        btnPay.setBorder(null);
        btnPay.setContentAreaFilled(false);
        btnPay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPay.setOpaque(true);
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe Print", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SkyCab");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("[ X ]");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTitleLayout = new javax.swing.GroupLayout(pnlTitle);
        pnlTitle.setLayout(pnlTitleLayout);
        pnlTitleLayout.setHorizontalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
        );
        pnlTitleLayout.setVerticalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTitleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pfCVV.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        pfCVV.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pfCVVFocusLost(evt);
            }
        });

        lblCardNoError.setForeground(new java.awt.Color(255, 255, 255));
        lblCardNoError.setText("jLabel6");

        lblCardNameError.setForeground(new java.awt.Color(255, 255, 255));
        lblCardNameError.setText("jLabel6");

        lblCVVNoError.setForeground(new java.awt.Color(255, 255, 255));
        lblCVVNoError.setText("jLabel6");

        tfAmt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfAmt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        javax.swing.GroupLayout pnlPayLayout = new javax.swing.GroupLayout(pnlPay);
        pnlPay.setLayout(pnlPayLayout);
        pnlPayLayout.setHorizontalGroup(
            pnlPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPayLayout.createSequentialGroup()
                .addGroup(pnlPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlPayLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblCardNameError))
                    .addGroup(pnlPayLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCardNoError))
                    .addGroup(pnlPayLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pnlPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfCardNo)
                            .addGroup(pnlPayLayout.createSequentialGroup()
                                .addComponent(lblCardNo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 342, Short.MAX_VALUE)
                                .addGroup(pnlPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPayLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(49, 49, 49))
                                    .addGroup(pnlPayLayout.createSequentialGroup()
                                        .addGroup(pnlPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPayLayout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(64, 64, 64))
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4))))
                            .addGroup(pnlPayLayout.createSequentialGroup()
                                .addComponent(lblCardName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(tfCardName)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPayLayout.createSequentialGroup()
                                .addGroup(pnlPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlPayLayout.createSequentialGroup()
                                        .addComponent(lblCvvNo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlPayLayout.createSequentialGroup()
                                        .addComponent(lblExpiry)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlPayLayout.createSequentialGroup()
                                        .addGroup(pnlPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(pfCVV, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnlPayLayout.createSequentialGroup()
                                                .addComponent(cbExpiryDate, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(chExpiryYr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblCVVNoError)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                                .addGroup(pnlPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIssueNo)
                                    .addComponent(tfIssueNo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblValid)
                                    .addComponent(tfAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(24, 24, 24))
            .addGroup(pnlPayLayout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPayLayout.setVerticalGroup(
            pnlPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPayLayout.createSequentialGroup()
                .addComponent(pnlTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(pnlPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnlPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCardNo)
                        .addComponent(lbl1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfCardNo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCardNoError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl2)
                    .addComponent(lblCardName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfCardName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCardNameError)
                .addGap(3, 3, 3)
                .addGroup(pnlPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCvvNo)
                    .addComponent(lblIssueNo)
                    .addComponent(lbl3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfIssueNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pfCVV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCVVNoError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl4)
                    .addGroup(pnlPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblExpiry)
                        .addComponent(lblValid)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfAmt, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(cbExpiryDate)
                    .addComponent(chExpiryYr))
                .addGap(50, 50, 50)
                .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfCardNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCardNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCardNoActionPerformed

    private void tfCardNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCardNoKeyPressed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_tfCardNoKeyPressed

    private void tfCardNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCardNoKeyTyped
        // TODO add your handling code here: 
    }//GEN-LAST:event_tfCardNoKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfCardNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCardNoFocusLost
        // TODO add your handling code here:
         
        if(tfCardNo.getText().equals("")){
            tfCardNo.setBorder(BorderFactory.createLineBorder(Color.red, 1, true));
            tfCardNo.setBackground(new Color(255,255,204));
            lblCardNoError.setForeground(Color.red);
            lblCardNoError.setText("Enter your Card No.");
        }
        else if(tfCardNo.getText().length()<12){
            tfCardNo.setBorder(BorderFactory.createLineBorder(Color.red, 1, true));
            tfCardNo.setBackground(new Color(255,255,204));
            lblCardNoError.setForeground(Color.red);
            lblCardNoError.setText("Card No. cannot be less than 12 characters");
        }
        else{
            tfCardNo.setBorder(BorderFactory.createLineBorder(new Color(153,153,153), 1, true));
            tfCardNo.setBackground(new Color(255,255,255));
            lblCardNoError.setForeground(Color.white);
            //lblCardNoError.setText("Card No. cannot be less than 12 characters");
            isCardNoValid=true;
        }
    }//GEN-LAST:event_tfCardNoFocusLost

    private void tfCardNoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCardNoFocusGained
        // TODO add your handling code here:
        //((AbstractDocument)tfCardNo.getDocument()).setDocumentFilter(new NumberDocumentFilter());
    }//GEN-LAST:event_tfCardNoFocusGained

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        // TODO add your handling code here:
        int issueNo;
        if(tfIssueNo.getText().equals("")){
            issueNo=0;
        }
        else{
            issueNo=Integer.parseInt(tfIssueNo.getText());
        }
        if(isCardNoValid && isCardNameValid && isCVVNoValid){
            try{
            if(new DatabaseConnection().bookTicketandPayment(Booking.name,Booking.age,Booking.gender,Booking.IdCardType,Booking.IdCardNo,Booking.Food,Booking.Senior,Search.doj,Search.dor,Search.classOfJourney,Login.Cust_Id,FlightPopUp.fid,Long.parseLong(tfCardNo.getText()),tfCardName.getText(),Integer.parseInt(String.valueOf(pfCVV.getPassword())),issueNo,FlightPopUp.amt)){
                JOptionPane.showMessageDialog(this,"Tickets Booked Successfully","Booking",JOptionPane.INFORMATION_MESSAGE);
                new Print();
                dispose();
            }
            else{
                JOptionPane.showMessageDialog(this,"Some Error Occured","Payment",JOptionPane.ERROR_MESSAGE);
            }
            
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this,e.toString(),"Exception",JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_btnPayActionPerformed

    private void tfCardNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCardNameFocusLost
        // TODO add your handling code here:
        
        if(tfCardName.getText().equals("")){
            tfCardName.setBorder(BorderFactory.createLineBorder(Color.red, 1, true));
            tfCardName.setBackground(new Color(255,255,204));
            lblCardNameError.setForeground(Color.red);
            lblCardNameError.setText("Enter your Name");
        }
        else{
            tfCardName.setBorder(BorderFactory.createLineBorder(new Color(153,153,153), 1, true));
            tfCardName.setBackground(new Color(255,255,255));
            lblCardNameError.setForeground(Color.white);
            //lblCardNoError.setText("Card No. cannot be less than 12 characters");
            isCardNameValid=true;
        }
    }//GEN-LAST:event_tfCardNameFocusLost

    private void pfCVVFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfCVVFocusLost
        // TODO add your handling code here:
        if(String.valueOf(pfCVV.getPassword()).equals("")){
            pfCVV.setBorder(BorderFactory.createLineBorder(Color.red, 1, true));
            pfCVV.setBackground(new Color(255,255,204));
            lblCVVNoError.setForeground(Color.red);
            lblCVVNoError.setText("Enter your CVV No.");
        }
        else{
            pfCVV.setBorder(BorderFactory.createLineBorder(new Color(153,153,153), 1, true));
            pfCVV.setBackground(new Color(255,255,255));
            lblCVVNoError.setForeground(Color.white);
            isCVVNoValid=true;
        }
    }//GEN-LAST:event_pfCVVFocusLost

    /**
     * @param args the command line arguments
     */
    
    public class NumberDocumentFilter extends DocumentFilter{
        public void insert(DocumentFilter.FilterBypass fp,int off,String string,AttributeSet attr) throws BadLocationException{
            int len=string.length();
            boolean isValidNum=true;
            
            for(int i=0;i<len;i++){
                if(!(Character.isDigit(string.charAt(i)))){
                    isValidNum=false;
                    break;
                }    
            }
            if(isValidNum){
                super.insertString(fp, off, string, attr);
                //fp.insertString(off,string.replaceAll("\\d",""),as);
            }
            else{
                Toolkit.getDefaultToolkit().beep();
            }  
        }
        
        public void replace(DocumentFilter.FilterBypass fp,int off,int length,String string,AttributeSet attr) throws BadLocationException{
            int len=string.length();
            boolean isValidNum=true;
            
            for(int i=0;i<len;i++){
                if(!(Character.isDigit(string.charAt(i)))){
                    isValidNum=false;
                    break;
                }
            }
            if(isValidNum){
                super.insertString(fp, off, string, attr);
                //fp.insertString(off,string.replaceAll("\\d",""),as);
            }
            else{
                Toolkit.getDefaultToolkit().beep();
            }  
        }
        
    }
    
    public class CharDocumentFilter extends DocumentFilter{
        public void insert(DocumentFilter.FilterBypass fp,int off,String string,AttributeSet attr) throws BadLocationException{
            int len=string.length();
            boolean isValidChar=true;
            
            for(int i=0;i<len;i++){
                if(!( Character.isWhitespace(string.charAt(i)) || ((int)string.charAt(i))==39 || Character.isLetter(string.charAt(i)))){
                    isValidChar=false;
                    break;
                }    
            }
            if(isValidChar){
                super.insertString(fp, off, string, attr);
                //fp.insertString(off,string.replaceAll("\\d",""),as);
            }
            else{
                Toolkit.getDefaultToolkit().beep();
            }  
        }
        
        public void replace(DocumentFilter.FilterBypass fp,int off,int length,String string,AttributeSet attr) throws BadLocationException{
            int len=string.length();
            boolean isValidChar=true;
            
            for(int i=0;i<len;i++){
                if(!(Character.isWhitespace(string.charAt(i)) || ((int)string.charAt(i))==39 || Character.isLetter(string.charAt(i)))){
                    isValidChar=false;
                    break;
                }
            }
            if(isValidChar){
                super.insertString(fp, off, string, attr);
                //fp.insertString(off,string.replaceAll("\\d",""),as);
            }
            else{
                Toolkit.getDefaultToolkit().beep();
            }  
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPay;
    private javax.swing.JComboBox cbExpiryDate;
    private javax.swing.JComboBox chExpiryYr;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lblCVVNoError;
    private javax.swing.JLabel lblCardName;
    private javax.swing.JLabel lblCardNameError;
    private javax.swing.JLabel lblCardNo;
    private javax.swing.JLabel lblCardNoError;
    private javax.swing.JLabel lblCvvNo;
    private javax.swing.JLabel lblExpiry;
    private javax.swing.JLabel lblIssueNo;
    private javax.swing.JLabel lblValid;
    private javax.swing.JPasswordField pfCVV;
    private javax.swing.JPanel pnlPay;
    private javax.swing.JPanel pnlTitle;
    private javax.swing.JTextField tfAmt;
    private javax.swing.JTextField tfCardName;
    private javax.swing.JTextField tfCardNo;
    private javax.swing.JTextField tfIssueNo;
    // End of variables declaration//GEN-END:variables
}
