package airline.reservation.system;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Michael
 */
import airlineDB.DatabaseConnection;
import java.awt.*;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.swing.*;
import javax.swing.border.Border;
import javax.swing.text.*;
import java.sql.*;
public class Registration extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form Registration
     */
    
    CardLayout cards;
    String FNameInitVal="First Name", LNameInitVal="Last Name", addressInitVal="Address", emailInitVal="Email", altEmailInitVal="Alternate Email (Optional)", contactInitVal="Contact No.", userNameInitVal="UserName", pswdInitVal="Password", cnfpswdInitVal="Confirm Password";
    ImageIcon wrong;
    ImageIcon right;
    boolean FNameErr=false,LNameErr=false,addressErr=false,emailErr=false,altEmailErr=false,contactErr=false,userNameErr=false,pswdErr=false,cnfPswdErr=false;
    public Registration(){
        initComponents();
        ((AbstractDocument)tfFName.getDocument()).setDocumentFilter(new CharDocumentFilter());
        
        
        UIManager.put("ToolTip.background", new javax.swing.plaf.ColorUIResource(255,255,204)); 
        Border border = BorderFactory.createLineBorder(new Color(255,0,0));    
        UIManager.put("ToolTip.border", border);
         ToolTipManager.sharedInstance().setInitialDelay(100);
        ToolTipManager.sharedInstance().setDismissDelay(15000); 
        
        wrong=new ImageIcon(getClass().getResource("wrong.png"));
        right=new ImageIcon(getClass().getResource("right.png"));
        
        setLocationRelativeTo(null);
        setOpacity(0.0f);
        Thread t1=new Thread(this);
        t1.start();
        setVisible(true);
        
    }
    
     public void run(){
        try{
            for(float i=0.0f;i<=0.92f;i+=0.01){
                setOpacity(i);
                Thread.sleep(5);
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        pnlProgress = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jlpProgress = new javax.swing.JLayeredPane();
        lbl2 = new javax.swing.JLabel();
        jsp2to3 = new javax.swing.JSeparator();
        jsp1to2 = new javax.swing.JSeparator();
        lbl1 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        pnlCardHolder = new javax.swing.JPanel();
        pnlPersonalDetails = new javax.swing.JPanel();
        lblPersonalDetails = new javax.swing.JLabel();
        btnPNext = new javax.swing.JButton();
        jlpFName = new javax.swing.JLayeredPane();
        tfFName = new javax.swing.JTextField();
        jlpLName = new javax.swing.JLayeredPane();
        tfLName = new javax.swing.JTextField();
        jlpAddress = new javax.swing.JLayeredPane();
        jspAddress = new javax.swing.JScrollPane();
        taAddress = new javax.swing.JTextArea();
        lblFNameError = new javax.swing.JLabel();
        lblAddressError = new javax.swing.JLabel();
        lblLNameError = new javax.swing.JLabel();
        pnlContactDetails = new javax.swing.JPanel();
        lblContactDetails = new javax.swing.JLabel();
        btnCPrevious = new javax.swing.JButton();
        btnCNext = new javax.swing.JButton();
        jlpEmail = new javax.swing.JLayeredPane();
        tfEmail = new javax.swing.JTextField();
        jlpAltEmail = new javax.swing.JLayeredPane();
        tfAltEmail = new javax.swing.JTextField();
        jlpContactNo = new javax.swing.JLayeredPane();
        tfContactNo = new javax.swing.JTextField();
        lblEmailError = new javax.swing.JLabel();
        lblAltEmailError = new javax.swing.JLabel();
        lblContactError = new javax.swing.JLabel();
        lblEmailErrorMsg = new javax.swing.JLabel();
        lblAltEmailErrorMsg = new javax.swing.JLabel();
        pnlAccountSetup = new javax.swing.JPanel();
        lblAccountSetup = new javax.swing.JLabel();
        btnAPrevious = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        jlpUserName = new javax.swing.JLayeredPane();
        tfUserName = new javax.swing.JTextField();
        jlpPassword = new javax.swing.JLayeredPane();
        pfPassword = new javax.swing.JPasswordField();
        jlpConfirmPassword = new javax.swing.JLayeredPane();
        pfConfirmPassword = new javax.swing.JPasswordField();
        lblUserNameError = new javax.swing.JLabel();
        lblPasswordError = new javax.swing.JLabel();
        lblCnfPasswordError = new javax.swing.JLabel();
        lblUserNameErrorMsg = new javax.swing.JLabel();
        lblPasswordErrorMsg = new javax.swing.JLabel();
        lblCnfPasswordErrorMsg = new javax.swing.JLabel();
        pnlLogo = new javax.swing.JPanel();
        jlpLogo = new javax.swing.JLayeredPane();
        lblName = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setOpacity(0.9f);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlBackground.setBackground(new java.awt.Color(255, 255, 255));

        pnlProgress.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton1.setText("[ X ]");
        jButton1.setToolTipText("");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lbl2.setBackground(new java.awt.Color(255, 255, 255));
        lbl2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl2.setText("2");
        lbl2.setOpaque(true);

        jsp2to3.setOpaque(true);

        jsp1to2.setOpaque(true);

        lbl1.setBackground(new java.awt.Color(255, 255, 255));
        lbl1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl1.setText("1");
        lbl1.setOpaque(true);

        lbl3.setBackground(new java.awt.Color(255, 255, 255));
        lbl3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl3.setText("3");
        lbl3.setOpaque(true);

        jlpProgress.setLayer(lbl2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpProgress.setLayer(jsp2to3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpProgress.setLayer(jsp1to2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpProgress.setLayer(lbl1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpProgress.setLayer(lbl3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpProgressLayout = new javax.swing.GroupLayout(jlpProgress);
        jlpProgress.setLayout(jlpProgressLayout);
        jlpProgressLayout.setHorizontalGroup(
            jlpProgressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpProgressLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsp1to2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsp2to3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jlpProgressLayout.setVerticalGroup(
            jlpProgressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpProgressLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpProgressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpProgressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lbl1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jlpProgressLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jlpProgressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpProgressLayout.createSequentialGroup()
                                .addComponent(jsp1to2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpProgressLayout.createSequentialGroup()
                                .addComponent(jsp2to3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)))))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlProgressLayout = new javax.swing.GroupLayout(pnlProgress);
        pnlProgress.setLayout(pnlProgressLayout);
        pnlProgressLayout.setHorizontalGroup(
            pnlProgressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProgressLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jlpProgress)
                .addGap(37, 37, 37)
                .addComponent(jButton1)
                .addContainerGap())
        );
        pnlProgressLayout.setVerticalGroup(
            pnlProgressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProgressLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProgressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProgressLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jlpProgress, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        pnlCardHolder.setBackground(new java.awt.Color(255, 255, 255));
        pnlCardHolder.setLayout(new java.awt.CardLayout());

        pnlPersonalDetails.setBackground(new java.awt.Color(255, 255, 255));

        lblPersonalDetails.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPersonalDetails.setForeground(new java.awt.Color(51, 51, 51));
        lblPersonalDetails.setText("PERSONAL DETAILS");

        btnPNext.setBackground(new java.awt.Color(51, 102, 255));
        btnPNext.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnPNext.setForeground(new java.awt.Color(255, 255, 255));
        btnPNext.setText("Next");
        btnPNext.setBorder(null);
        btnPNext.setContentAreaFilled(false);
        btnPNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPNext.setOpaque(true);
        btnPNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPNextActionPerformed(evt);
            }
        });

        jlpFName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jlpFName.setOpaque(true);

        tfFName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfFName.setText("First Name");
        tfFName.setBorder(null);
        tfFName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfFNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfFNameFocusLost(evt);
            }
        });
        tfFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFNameActionPerformed(evt);
            }
        });

        jlpFName.setLayer(tfFName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpFNameLayout = new javax.swing.GroupLayout(jlpFName);
        jlpFName.setLayout(jlpFNameLayout);
        jlpFNameLayout.setHorizontalGroup(
            jlpFNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpFNameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfFName, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jlpFNameLayout.setVerticalGroup(
            jlpFNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpFNameLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tfFName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jlpLName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jlpLName.setOpaque(true);

        tfLName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfLName.setText("Last Name");
        tfLName.setBorder(null);
        tfLName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfLNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfLNameFocusLost(evt);
            }
        });

        jlpLName.setLayer(tfLName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpLNameLayout = new javax.swing.GroupLayout(jlpLName);
        jlpLName.setLayout(jlpLNameLayout);
        jlpLNameLayout.setHorizontalGroup(
            jlpLNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpLNameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tfLName, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jlpLNameLayout.setVerticalGroup(
            jlpLNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpLNameLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tfLName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jlpAddress.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jlpAddress.setOpaque(true);

        jspAddress.setBorder(null);

        taAddress.setColumns(20);
        taAddress.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        taAddress.setRows(5);
        taAddress.setText("Address");
        taAddress.setBorder(null);
        taAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                taAddressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                taAddressFocusLost(evt);
            }
        });
        jspAddress.setViewportView(taAddress);

        jlpAddress.setLayer(jspAddress, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpAddressLayout = new javax.swing.GroupLayout(jlpAddress);
        jlpAddress.setLayout(jlpAddressLayout);
        jlpAddressLayout.setHorizontalGroup(
            jlpAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAddressLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jspAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jlpAddressLayout.setVerticalGroup(
            jlpAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAddressLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jspAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lblFNameError.setForeground(new java.awt.Color(51, 51, 51));
        lblFNameError.setDoubleBuffered(true);

        javax.swing.GroupLayout pnlPersonalDetailsLayout = new javax.swing.GroupLayout(pnlPersonalDetails);
        pnlPersonalDetails.setLayout(pnlPersonalDetailsLayout);
        pnlPersonalDetailsLayout.setHorizontalGroup(
            pnlPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPersonalDetailsLayout.createSequentialGroup()
                .addGroup(pnlPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPersonalDetailsLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(lblPersonalDetails))
                    .addGroup(pnlPersonalDetailsLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(pnlPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlpLName)
                            .addComponent(jlpAddress)
                            .addComponent(jlpFName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFNameError)
                            .addComponent(lblLNameError)
                            .addComponent(lblAddressError))))
                .addGap(0, 84, Short.MAX_VALUE))
            .addGroup(pnlPersonalDetailsLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(btnPNext, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPersonalDetailsLayout.setVerticalGroup(
            pnlPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPersonalDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPersonalDetails)
                .addGroup(pnlPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPersonalDetailsLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jlpFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPersonalDetailsLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblFNameError)))
                .addGroup(pnlPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPersonalDetailsLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlpLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(pnlPersonalDetailsLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblLNameError)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(pnlPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlpAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlPersonalDetailsLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblAddressError)))
                .addGap(33, 33, 33)
                .addComponent(btnPNext, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pnlCardHolder.add(pnlPersonalDetails, "cardPD");

        pnlContactDetails.setBackground(new java.awt.Color(255, 255, 255));

        lblContactDetails.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblContactDetails.setForeground(new java.awt.Color(51, 51, 51));
        lblContactDetails.setText("CONTACT DETAILS");

        btnCPrevious.setBackground(new java.awt.Color(51, 102, 255));
        btnCPrevious.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnCPrevious.setForeground(new java.awt.Color(255, 255, 255));
        btnCPrevious.setText("Previous");
        btnCPrevious.setBorder(null);
        btnCPrevious.setContentAreaFilled(false);
        btnCPrevious.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCPrevious.setOpaque(true);
        btnCPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCPreviousActionPerformed(evt);
            }
        });

        btnCNext.setBackground(new java.awt.Color(51, 102, 255));
        btnCNext.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnCNext.setForeground(new java.awt.Color(255, 255, 255));
        btnCNext.setText("Next");
        btnCNext.setBorder(null);
        btnCNext.setContentAreaFilled(false);
        btnCNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCNext.setOpaque(true);
        btnCNext.setPreferredSize(new java.awt.Dimension(49, 30));
        btnCNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCNextActionPerformed(evt);
            }
        });

        jlpEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jlpEmail.setOpaque(true);

        tfEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfEmail.setText("Email");
        tfEmail.setBorder(null);
        tfEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfEmailFocusLost(evt);
            }
        });
        tfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailActionPerformed(evt);
            }
        });

        jlpEmail.setLayer(tfEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpEmailLayout = new javax.swing.GroupLayout(jlpEmail);
        jlpEmail.setLayout(jlpEmailLayout);
        jlpEmailLayout.setHorizontalGroup(
            jlpEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpEmailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jlpEmailLayout.setVerticalGroup(
            jlpEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpEmailLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jlpAltEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jlpAltEmail.setOpaque(true);

        tfAltEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfAltEmail.setText("Alternate Email (Optional)");
        tfAltEmail.setBorder(null);
        tfAltEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfAltEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfAltEmailFocusLost(evt);
            }
        });
        tfAltEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAltEmailActionPerformed(evt);
            }
        });

        jlpAltEmail.setLayer(tfAltEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpAltEmailLayout = new javax.swing.GroupLayout(jlpAltEmail);
        jlpAltEmail.setLayout(jlpAltEmailLayout);
        jlpAltEmailLayout.setHorizontalGroup(
            jlpAltEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAltEmailLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tfAltEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jlpAltEmailLayout.setVerticalGroup(
            jlpAltEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAltEmailLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tfAltEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jlpContactNo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jlpContactNo.setOpaque(true);

        tfContactNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfContactNo.setText("Contact No.");
        tfContactNo.setBorder(null);
        tfContactNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfContactNoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfContactNoFocusLost(evt);
            }
        });
        tfContactNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfContactNoActionPerformed(evt);
            }
        });

        jlpContactNo.setLayer(tfContactNo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpContactNoLayout = new javax.swing.GroupLayout(jlpContactNo);
        jlpContactNo.setLayout(jlpContactNoLayout);
        jlpContactNoLayout.setHorizontalGroup(
            jlpContactNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpContactNoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jlpContactNoLayout.setVerticalGroup(
            jlpContactNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpContactNoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tfContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lblEmailErrorMsg.setForeground(new java.awt.Color(255, 255, 255));
        lblEmailErrorMsg.setText("jLabel1");

        lblAltEmailErrorMsg.setForeground(new java.awt.Color(255, 255, 255));
        lblAltEmailErrorMsg.setText("jLabel2");

        javax.swing.GroupLayout pnlContactDetailsLayout = new javax.swing.GroupLayout(pnlContactDetails);
        pnlContactDetails.setLayout(pnlContactDetailsLayout);
        pnlContactDetailsLayout.setHorizontalGroup(
            pnlContactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContactDetailsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlContactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContactDetailsLayout.createSequentialGroup()
                        .addComponent(lblContactDetails)
                        .addGap(151, 151, 151))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContactDetailsLayout.createSequentialGroup()
                        .addComponent(lblEmailErrorMsg)
                        .addGap(125, 125, 125))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContactDetailsLayout.createSequentialGroup()
                        .addComponent(lblAltEmailErrorMsg)
                        .addGap(124, 124, 124))))
            .addGroup(pnlContactDetailsLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(pnlContactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContactDetailsLayout.createSequentialGroup()
                        .addComponent(btnCPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(btnCNext, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125))
                    .addGroup(pnlContactDetailsLayout.createSequentialGroup()
                        .addGroup(pnlContactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlContactDetailsLayout.createSequentialGroup()
                                .addComponent(jlpAltEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblAltEmailError))
                            .addGroup(pnlContactDetailsLayout.createSequentialGroup()
                                .addComponent(jlpEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblEmailError))
                            .addGroup(pnlContactDetailsLayout.createSequentialGroup()
                                .addComponent(jlpContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblContactError)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlContactDetailsLayout.setVerticalGroup(
            pnlContactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContactDetailsLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblContactDetails)
                .addGroup(pnlContactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContactDetailsLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jlpEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlContactDetailsLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lblEmailError)))
                .addGroup(pnlContactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContactDetailsLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblEmailErrorMsg)
                        .addGap(9, 9, 9)
                        .addComponent(jlpAltEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlContactDetailsLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lblAltEmailError)))
                .addGroup(pnlContactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContactDetailsLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblAltEmailErrorMsg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlpContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlContactDetailsLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lblContactError)))
                .addGap(40, 40, 40)
                .addGroup(pnlContactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCNext, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pnlCardHolder.add(pnlContactDetails, "cardCD");

        pnlAccountSetup.setBackground(new java.awt.Color(255, 255, 255));

        lblAccountSetup.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAccountSetup.setForeground(new java.awt.Color(51, 51, 51));
        lblAccountSetup.setText("ACCOUNT SETUP");

        btnAPrevious.setBackground(new java.awt.Color(51, 102, 255));
        btnAPrevious.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAPrevious.setForeground(new java.awt.Color(255, 255, 255));
        btnAPrevious.setText("Previous");
        btnAPrevious.setBorder(null);
        btnAPrevious.setContentAreaFilled(false);
        btnAPrevious.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAPrevious.setOpaque(true);
        btnAPrevious.setPreferredSize(new java.awt.Dimension(89, 30));
        btnAPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAPreviousActionPerformed(evt);
            }
        });

        btnSubmit.setBackground(new java.awt.Color(51, 102, 255));
        btnSubmit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.setBorder(null);
        btnSubmit.setContentAreaFilled(false);
        btnSubmit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSubmit.setOpaque(true);
        btnSubmit.setPreferredSize(new java.awt.Dimension(73, 30));
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jlpUserName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jlpUserName.setOpaque(true);

        tfUserName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfUserName.setText("UserName");
        tfUserName.setBorder(null);
        tfUserName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfUserNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfUserNameFocusLost(evt);
            }
        });
        tfUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUserNameActionPerformed(evt);
            }
        });

        jlpUserName.setLayer(tfUserName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpUserNameLayout = new javax.swing.GroupLayout(jlpUserName);
        jlpUserName.setLayout(jlpUserNameLayout);
        jlpUserNameLayout.setHorizontalGroup(
            jlpUserNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpUserNameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfUserName))
        );
        jlpUserNameLayout.setVerticalGroup(
            jlpUserNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpUserNameLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tfUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jlpPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jlpPassword.setOpaque(true);

        pfPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pfPassword.setText("Password");
        pfPassword.setBorder(null);
        pfPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pfPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pfPasswordFocusLost(evt);
            }
        });
        pfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfPasswordActionPerformed(evt);
            }
        });

        jlpPassword.setLayer(pfPassword, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpPasswordLayout = new javax.swing.GroupLayout(jlpPassword);
        jlpPassword.setLayout(jlpPasswordLayout);
        jlpPasswordLayout.setHorizontalGroup(
            jlpPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpPasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pfPassword))
        );
        jlpPasswordLayout.setVerticalGroup(
            jlpPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpPasswordLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jlpConfirmPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jlpConfirmPassword.setOpaque(true);

        pfConfirmPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pfConfirmPassword.setText("Confirm Password");
        pfConfirmPassword.setBorder(null);
        pfConfirmPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pfConfirmPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pfConfirmPasswordFocusLost(evt);
            }
        });
        pfConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfConfirmPasswordActionPerformed(evt);
            }
        });

        jlpConfirmPassword.setLayer(pfConfirmPassword, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpConfirmPasswordLayout = new javax.swing.GroupLayout(jlpConfirmPassword);
        jlpConfirmPassword.setLayout(jlpConfirmPasswordLayout);
        jlpConfirmPasswordLayout.setHorizontalGroup(
            jlpConfirmPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpConfirmPasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pfConfirmPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE))
        );
        jlpConfirmPasswordLayout.setVerticalGroup(
            jlpConfirmPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpConfirmPasswordLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pfConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lblUserNameErrorMsg.setForeground(new java.awt.Color(255, 255, 255));
        lblUserNameErrorMsg.setText("jLabel2");

        lblPasswordErrorMsg.setForeground(new java.awt.Color(255, 255, 255));
        lblPasswordErrorMsg.setText("jLabel1");

        lblCnfPasswordErrorMsg.setForeground(new java.awt.Color(255, 255, 255));
        lblCnfPasswordErrorMsg.setText("jLabel1");

        javax.swing.GroupLayout pnlAccountSetupLayout = new javax.swing.GroupLayout(pnlAccountSetup);
        pnlAccountSetup.setLayout(pnlAccountSetupLayout);
        pnlAccountSetupLayout.setHorizontalGroup(
            pnlAccountSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAccountSetupLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
            .addGroup(pnlAccountSetupLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlAccountSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jlpPassword)
                    .addComponent(jlpUserName)
                    .addComponent(jlpConfirmPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAccountSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUserNameError)
                    .addComponent(lblPasswordError)
                    .addComponent(lblCnfPasswordError))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAccountSetupLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUserNameErrorMsg)
                .addGap(120, 120, 120))
            .addGroup(pnlAccountSetupLayout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(lblAccountSetup)
                .addContainerGap(173, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAccountSetupLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPasswordErrorMsg)
                .addGap(118, 118, 118))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAccountSetupLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCnfPasswordErrorMsg)
                .addGap(116, 116, 116))
        );
        pnlAccountSetupLayout.setVerticalGroup(
            pnlAccountSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccountSetupLayout.createSequentialGroup()
                .addGroup(pnlAccountSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAccountSetupLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblAccountSetup)
                        .addGap(31, 31, 31)
                        .addComponent(jlpUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAccountSetupLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(lblUserNameError)))
                .addGroup(pnlAccountSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAccountSetupLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblUserNameErrorMsg)
                        .addGap(16, 16, 16)
                        .addComponent(jlpPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAccountSetupLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(lblPasswordError)))
                .addGroup(pnlAccountSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAccountSetupLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblPasswordErrorMsg)
                        .addGap(14, 14, 14)
                        .addComponent(jlpConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAccountSetupLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(lblCnfPasswordError)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCnfPasswordErrorMsg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAccountSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pnlCardHolder.add(pnlAccountSetup, "cardAS");

        pnlLogo.setBackground(new java.awt.Color(51, 51, 51));

        lblName.setFont(new java.awt.Font("Segoe Print", 0, 48)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("SkyCab");

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airline/reservation/system/airplane white.png"))); // NOI18N

        jlpLogo.setLayer(lblName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpLogo.setLayer(lblLogo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpLogoLayout = new javax.swing.GroupLayout(jlpLogo);
        jlpLogo.setLayout(jlpLogoLayout);
        jlpLogoLayout.setHorizontalGroup(
            jlpLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpLogoLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(lblName)
                .addContainerGap(118, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpLogoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jlpLogoLayout.setVerticalGroup(
            jlpLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpLogoLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlLogoLayout = new javax.swing.GroupLayout(pnlLogo);
        pnlLogo.setLayout(pnlLogoLayout);
        pnlLogoLayout.setHorizontalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLogoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlpLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        pnlLogoLayout.setVerticalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlpLogo, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addComponent(pnlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4))
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(pnlCardHolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addComponent(pnlProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pnlCardHolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFNameActionPerformed

    private void btnPNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPNextActionPerformed
      
        if(!(tfFName.getText().equals("First Name") || tfLName.getText().equals("Last Name") || taAddress.getText().equals("Address"))){
            if(!(FNameErr || LNameErr || addressErr)){
                cards=(CardLayout)pnlCardHolder.getLayout();
                cards.show(pnlCardHolder,"cardCD");
                jsp1to2.setBackground(new Color(51,153,255));
                lbl2.setBackground(new Color(0,204,0));
                lbl2.setForeground(Color.white);
            }
        }
        else{
            if(tfFName.getText().equals(FNameInitVal)){
                jlpFName.setBorder(BorderFactory.createLineBorder(Color.red,1,true));
                tfFName.setToolTipText("Enter your Name");
                lblFNameError.setIcon(wrong);
                jlpFName.setBackground(new Color(255,255,204));
                tfFName.setBackground(new Color(255,255,204));
                //ToolTipManager.sharedInstance().setInitialDelay(100);
            }
        
            if(tfLName.getText().equals(LNameInitVal)){
                jlpLName.setBorder(BorderFactory.createLineBorder(Color.red,1,true));
                tfLName.setToolTipText("Enter your Surname");
                lblLNameError.setIcon(wrong);
                jlpLName.setBackground(new Color(255,255,204));
                tfLName.setBackground(new Color(255,255,204));
                //ToolTipManager.sharedInstance().setInitialDelay(100);
            }
        
            if(taAddress.getText().equals(addressInitVal)){
                jlpAddress.setBorder(BorderFactory.createLineBorder(Color.red,1,true));
                taAddress.setToolTipText("Enter your Address");
                lblAddressError.setIcon(wrong);
                jlpAddress.setBackground(new Color(255,255,204));
                taAddress.setBackground(new Color(255,255,204));
               // ToolTipManager.sharedInstance().setInitialDelay(100);
            }
        }
        
    }//GEN-LAST:event_btnPNextActionPerformed

    private void pfConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfConfirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfConfirmPasswordActionPerformed

    private void btnAPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAPreviousActionPerformed
        // TODO add your handling code here:
        cards.show(pnlCardHolder,"cardCD");
        lbl3.setBackground(Color.white);
        lbl3.setForeground(Color.black);
        jsp2to3.setBackground(new Color(160,160,160));
    }//GEN-LAST:event_btnAPreviousActionPerformed

    private void tfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailActionPerformed

    private void tfContactNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfContactNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfContactNoActionPerformed

    private void tfAltEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAltEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAltEmailActionPerformed

    private void btnCPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCPreviousActionPerformed
        // TODO add your handling code here:
        cards.show(pnlCardHolder,"cardPD");
        lbl2.setBackground(Color.white);
        lbl2.setForeground(Color.black);
        jsp1to2.setBackground(new Color(160,160,160));
    }//GEN-LAST:event_btnCPreviousActionPerformed

    private void btnCNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCNextActionPerformed
        // TODO add your handling code here:
        if(!(tfEmail.getText().equals(emailInitVal) || tfContactNo.getText().equals(contactInitVal))){
            if(!(emailErr || altEmailErr || contactErr)){
                cards.show(pnlCardHolder,"cardAS");
                lbl3.setBackground(new Color(255,51,51));
                jsp2to3.setBackground(new Color(0,204,0));
                lbl3.setForeground(Color.white);
            }
        }
        else{
            if(tfEmail.getText().equals(emailInitVal)){
                jlpEmail.setBorder(BorderFactory.createLineBorder(Color.red,1,true));
                tfEmail.setToolTipText("Enter your Email");
                lblEmailError.setIcon(wrong);
                jlpEmail.setBackground(new Color(255,255,204));
                tfEmail.setBackground(new Color(255,255,204));
                //ToolTipManager.sharedInstance().setInitialDelay(100);
            }
        
            if(tfContactNo.getText().equals(contactInitVal)){
                jlpContactNo.setBorder(BorderFactory.createLineBorder(Color.red,1,true));
                tfContactNo.setToolTipText("Enter your Contact No.");
                lblContactError.setIcon(wrong);
                jlpContactNo.setBackground(new Color(255,255,204));
                tfContactNo.setBackground(new Color(255,255,204));
               // ToolTipManager.sharedInstance().setInitialDelay(100);
            }
        }
            
        
        
    }//GEN-LAST:event_btnCNextActionPerformed

    private void tfUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUserNameActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if(!(tfUserName.getText().equals(userNameInitVal) || String.valueOf(pfPassword.getPassword()).equals(pswdInitVal) || String.valueOf(pfConfirmPassword.getPassword()).equals(cnfpswdInitVal))){
            if(!(userNameErr || pswdErr || cnfPswdErr)){
                try{
                    boolean isRegistered=new DatabaseConnection().register(tfFName.getText(),tfLName.getText(),taAddress.getText(),tfEmail.getText(),tfAltEmail.getText(),Integer.parseInt(tfContactNo.getText()),tfUserName.getText(),String.valueOf(pfPassword.getPassword()));
                    if(isRegistered){
                        JOptionPane.showMessageDialog(this,"Registration Successful","Registration",JOptionPane.INFORMATION_MESSAGE);
                        new Login();
                        dispose();
                    }
                    else{
                        JOptionPane.showMessageDialog(this,"Some Error Occured while Inserting","Registration",JOptionPane.ERROR_MESSAGE);
                    }
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(this,e.toString(),"Exception",JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        else{
            if(tfUserName.getText().equals(userNameInitVal)){
                jlpUserName.setBorder(BorderFactory.createLineBorder(Color.red,1,true));
                jlpUserName.setBackground(new Color(255,255,204));
                tfUserName.setBackground(new Color(255,255,204));
                lblUserNameError.setIcon(wrong);
            }
            if(String.valueOf(pfPassword.getPassword()).equals(pswdInitVal)){
                jlpPassword.setBorder(BorderFactory.createLineBorder(Color.red,1,true));
                jlpPassword.setBackground(new Color(255,255,204));
                pfPassword.setBackground(new Color(255,255,204));
                lblPasswordError.setIcon(wrong);
            }
            if(String.valueOf(pfConfirmPassword.getPassword()).equals(cnfpswdInitVal)){
                jlpConfirmPassword.setBorder(BorderFactory.createLineBorder(Color.red,1,true));
                jlpConfirmPassword.setBackground(new Color(255,255,204));
                pfConfirmPassword.setBackground(new Color(255,255,204));
                lblCnfPasswordError.setIcon(wrong);
            }
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        pfPassword.setEchoChar((char)0);
        pfConfirmPassword.setEchoChar((char)0);
        lbl1.setBackground(new Color(51,153,255));
        lbl1.setForeground(Color.white);
            
        
        
    }//GEN-LAST:event_formWindowOpened

    private void tfFNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfFNameFocusGained
        // TODO add your handling code here:
        
        if(tfFName.getText().equals(FNameInitVal)){
            tfFName.setText("");
             
            //tfFName.setToolTipText("Enter your Name");
        }
       
    }//GEN-LAST:event_tfFNameFocusGained

    private void tfFNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfFNameFocusLost
        // TODO add your handling code here:
        
        if(tfFName.getText().length()==0){
            tfFName.setText(FNameInitVal);
        }
        
        if(tfFName.getText().length()==0 || tfFName.getText().equals(FNameInitVal)){
            tfFName.setToolTipText("Enter your Name");
            FNameErr=true;
        }
        else{
            FNameErr=false;
        }
        
        if(FNameErr){
            jlpFName.setBorder(BorderFactory.createLineBorder(Color.red,1,true));
            lblFNameError.setIcon(wrong);
            tfFName.setBackground(new Color(255,255,204));
            jlpFName.setBackground(new Color(255,255,204));
        }
        else{
            jlpFName.setBorder(BorderFactory.createLineBorder(new Color(153,153,153),1,true));
            lblFNameError.setIcon(right);
            tfFName.setToolTipText(null);
            tfFName.setBackground(new Color(255,255,255));
            jlpFName.setBackground(new Color(255,255,255));
            
        }
    }//GEN-LAST:event_tfFNameFocusLost

    private void pfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfPasswordActionPerformed

    private void tfLNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfLNameFocusGained
        // TODO add your handling code here:
        if(tfLName.getText().equals(LNameInitVal)){
            tfLName.setText("");
            //tfLName.setToolTipText("Enter your Surname");
        }
        ((AbstractDocument)tfLName.getDocument()).setDocumentFilter(new CharDocumentFilter());
    }//GEN-LAST:event_tfLNameFocusGained

    private void tfLNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfLNameFocusLost
        // TODO add your handling code here:
        //tfLName.setToolTipText(null);
      
        if(tfLName.getText().length()==0){
            tfLName.setText(LNameInitVal);
        }
        
        if(tfLName.getText().length()==0 || tfLName.getText().equals(LNameInitVal)){
            tfLName.setToolTipText("Enter your Surname");
            LNameErr=true;
        }
        else{
            LNameErr=false;
        }
        
        if(LNameErr){
            jlpLName.setBorder(BorderFactory.createLineBorder(Color.red,1,true));
            lblLNameError.setIcon(wrong);
            tfLName.setBackground(new Color(255,255,204));
            jlpLName.setBackground(new Color(255,255,204));
        }
        else{
            jlpLName.setBorder(BorderFactory.createLineBorder(new Color(153,153,153),1,true));
            lblLNameError.setIcon(right);
            tfLName.setToolTipText(null);
            tfLName.setBackground(new Color(255,255,255));
            jlpLName.setBackground(new Color(255,255,255));
            
        }
    }//GEN-LAST:event_tfLNameFocusLost

    private void taAddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_taAddressFocusGained
        // TODO add your handling code here:
        if(taAddress.getText().equals(addressInitVal)){
            taAddress.setText("");
            //taAddress.setToolTipText("Enter your Address");
        }
        
    }//GEN-LAST:event_taAddressFocusGained

    private void taAddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_taAddressFocusLost
        // TODO add your handling code here:
        //taAddress.setToolTipText(null);
       
        if(taAddress.getText().length()==0){
            taAddress.setText(addressInitVal);
        }
        
        if(taAddress.getText().length()==0 || taAddress.getText().equals(addressInitVal)){
            addressErr=true;
            taAddress.setToolTipText("Enter your Address");
        }
        else{
            addressErr=false;
        }
        
        if(addressErr){
            jlpAddress.setBorder(BorderFactory.createLineBorder(Color.red,1,true));
            lblAddressError.setIcon(wrong);
            jlpAddress.setBackground(new Color(255,255,204));
            taAddress.setBackground(new Color(255,255,204));
        }
        else{
            jlpAddress.setBorder(BorderFactory.createLineBorder(new Color(153,153,153),1,true));
            lblAddressError.setIcon(right);
            taAddress.setToolTipText(null);
            jlpAddress.setBackground(new Color(255,255,255));
            taAddress.setBackground(new Color(255,255,255));
        }
    }//GEN-LAST:event_taAddressFocusLost

    private void tfEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfEmailFocusGained
        // TODO add your handling code here:
        if(tfEmail.getText().equals(emailInitVal)){
            tfEmail.setText("");
            tfEmail.setToolTipText("Enter your Email");
        }
    }//GEN-LAST:event_tfEmailFocusGained

    private void tfAltEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfAltEmailFocusGained
        // TODO add your handling code here:
        if(tfAltEmail.getText().equals(altEmailInitVal)){
            tfAltEmail.setText("");
            tfAltEmail.setToolTipText("Enter your Alternate Email ID");
        }
    }//GEN-LAST:event_tfAltEmailFocusGained

    private void tfContactNoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfContactNoFocusGained
        // TODO add your handling code here:
        if(tfContactNo.getText().equals(contactInitVal)){
            tfContactNo.setText("");
            tfContactNo.setToolTipText("Enter your Contact No.");
        }
        ((AbstractDocument)tfContactNo.getDocument()).setDocumentFilter(new NumberDocumentFilter());
    }//GEN-LAST:event_tfContactNoFocusGained

    private void tfUserNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUserNameFocusGained
        // TODO add your handling code here:
        if(tfUserName.getText().equals(userNameInitVal)){
            tfUserName.setText("");
            tfUserName.setToolTipText("Enter your UserName");
        }
    }//GEN-LAST:event_tfUserNameFocusGained

    private void pfPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfPasswordFocusGained
        // TODO add your handling code here:
        if(String.valueOf(pfPassword.getPassword()).equals(pswdInitVal)){
            pfPassword.setText("");
            pfPassword.setEchoChar('\u25cf');
            pfPassword.setToolTipText("Enter your Password");
        }
    }//GEN-LAST:event_pfPasswordFocusGained

    private void pfConfirmPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfConfirmPasswordFocusGained
        // TODO add your handling code here:
        if(String.valueOf(pfConfirmPassword.getPassword()).equals(cnfpswdInitVal)){
            pfConfirmPassword.setText("");
            pfConfirmPassword.setEchoChar('\u25cf');
            pfConfirmPassword.setToolTipText("Re-enter your Password");
        }
    }//GEN-LAST:event_pfConfirmPasswordFocusGained

    private void pfConfirmPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfConfirmPasswordFocusLost
        // TODO add your handling code here:
        //pfConfirmPassword.setToolTipText(null);
        if(pfConfirmPassword.getPassword().length==0){
            pfConfirmPassword.setText(cnfpswdInitVal);
            pfConfirmPassword.setEchoChar((char)0);
        }
        
        if(pfConfirmPassword.getPassword().length==0 || String.valueOf(pfConfirmPassword.getPassword()).equals(cnfpswdInitVal)){
            
            pfConfirmPassword.setToolTipText("Confirm your Password");
        }
        else{
            if(String.valueOf(pfPassword.getPassword()).equals(String.valueOf(pfConfirmPassword.getPassword()))){
                cnfPswdErr=false;
            }
            else{
                lblCnfPasswordErrorMsg.setForeground(Color.red);
                lblCnfPasswordErrorMsg.setText("Passwords do not Match");
                cnfPswdErr=true;
            }
        }
        
        if(cnfPswdErr){
            jlpConfirmPassword.setBorder(BorderFactory.createLineBorder(Color.red,1,true));
            lblCnfPasswordError.setIcon(wrong);
            jlpConfirmPassword.setBackground(new Color(255,255,204));
            pfConfirmPassword.setBackground(new Color(255,255,204));
        }
        else{
            jlpConfirmPassword.setBorder(BorderFactory.createLineBorder(new Color(153,153,153),1,true));
            lblCnfPasswordError.setIcon(right);
            pfConfirmPassword.setToolTipText(null);
            jlpConfirmPassword.setBackground(new Color(255,255,255));
            pfConfirmPassword.setBackground(new Color(255,255,255));
            lblCnfPasswordErrorMsg.setForeground(Color.white);
        }
    }//GEN-LAST:event_pfConfirmPasswordFocusLost

    private void pfPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfPasswordFocusLost
        // TODO add your handling code here:
        //pfPassword.setToolTipText(null);
        
        if(pfPassword.getPassword().length==0){
            pfPassword.setText(pswdInitVal);
            pfPassword.setEchoChar((char)0);
        }
        
        if(pfPassword.getPassword().length==0 || String.valueOf(pfPassword.getPassword()).equals(pswdInitVal)){
            pfPassword.setToolTipText("Enter your Password");
            pswdErr=true;
        }
        else{
            if(pfPassword.getPassword().length<4 || pfPassword.getPassword().length>8){
                lblPasswordErrorMsg.setForeground(Color.red);
                lblPasswordErrorMsg.setText("Password should be between 4 to 8 chars");
                pswdErr=true;
            }
            else{
                pswdErr=false;
            }
        }
        
        if(pswdErr){
            jlpPassword.setBorder(BorderFactory.createLineBorder(Color.red,1,true));
            lblPasswordError.setIcon(wrong);
            jlpPassword.setBackground(new Color(255,255,204));
            pfPassword.setBackground(new Color(255,255,204));
        }
        else{
            jlpPassword.setBorder(BorderFactory.createLineBorder(new Color(153,153,153),1,true));
            lblPasswordError.setIcon(right);
            pfPassword.setToolTipText(null);
            jlpPassword.setBackground(new Color(255,255,255));
            pfPassword.setBackground(new Color(255,255,255));
            lblPasswordErrorMsg.setForeground(Color.white);
            
        }
    }//GEN-LAST:event_pfPasswordFocusLost

    private void tfUserNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUserNameFocusLost
        // TODO add your handling code here:
        //tfUserName.setToolTipText(null);
        if(tfUserName.getText().length()==0){
            tfUserName.setText(userNameInitVal);
        }
        
        if(tfUserName.getText().length()==0 || tfUserName.getText().equals(userNameInitVal)){
            tfUserName.setToolTipText("Enter your UserName");
            userNameErr=true;
        }
        else{
            try{
                if(!(new DatabaseConnection().checkUsername(tfUserName.getText()))){
                    userNameErr=true;
                    lblUserNameErrorMsg.setForeground(Color.red);
                    lblUserNameErrorMsg.setText("UserName not Available");
                }
                else{
                    userNameErr=false;
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this, e.toString(),"Exception",JOptionPane.ERROR_MESSAGE);
            }
        }
        
        if(userNameErr){
            jlpUserName.setBorder(BorderFactory.createLineBorder(Color.red,1,true));
            lblUserNameError.setIcon(wrong);
            jlpUserName.setBackground(new Color(255,255,204));
            tfUserName.setBackground(new Color(255,255,204));
        }
        else{
            jlpUserName.setBorder(BorderFactory.createLineBorder(new Color(153,153,153),1,true));
            lblUserNameError.setIcon(right);
            tfUserName.setToolTipText(null);
            jlpUserName.setBackground(new Color(255,255,255));
            tfUserName.setBackground(new Color(255,255,255));
            lblUserNameErrorMsg.setForeground(Color.white);
        }
    }//GEN-LAST:event_tfUserNameFocusLost

    private void tfContactNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfContactNoFocusLost
        // TODO add your handling code here:
        //tfContactNo.setToolTipText(null);
        
        if(tfContactNo.getText().length()==0){
            tfContactNo.setText(contactInitVal);
        }
        
        if(tfContactNo.getText().length()==0 || tfContactNo.getText().equals(contactInitVal)){
            contactErr=true;
            tfContactNo.setToolTipText("Enter your Contact No.");
        }
        else{
            contactErr=false;
        }
        
        if(contactErr){
            jlpContactNo.setBorder(BorderFactory.createLineBorder(Color.red,1,true));
            lblContactError.setIcon(wrong);
            jlpContactNo.setBackground(new Color(255,255,204));
            tfContactNo.setBackground(new Color(255,255,204));
        }
        else{
            jlpContactNo.setBorder(BorderFactory.createLineBorder(new Color(153,153,153),1,true));
            lblContactError.setIcon(right);
            tfContactNo.setToolTipText(null);
            jlpContactNo.setBackground(new Color(255,255,255));
            tfContactNo.setBackground(new Color(255,255,255));
            
        }
    
    }//GEN-LAST:event_tfContactNoFocusLost

    private void tfAltEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfAltEmailFocusLost
        // TODO add your handling code here:
        //tfAltEmail.setToolTipText(null);
       
        boolean res;
       if(tfAltEmail.getText().length()==0){
            tfAltEmail.setText(altEmailInitVal);
        }
        
        if(tfAltEmail.getText().length()==0 || tfAltEmail.getText().equals(altEmailInitVal)){
            altEmailErr=false;
            
        }
        else{
            res=isValidEmailAddress(tfAltEmail.getText());
            if(!res){
                altEmailErr=true;
                lblAltEmailErrorMsg.setForeground(Color.red);
                lblAltEmailErrorMsg.setText("Invalid Email Address");
            }
            else if(tfEmail.getText().equals(tfAltEmail.getText())){
                lblAltEmailErrorMsg.setForeground(Color.red);
                lblAltEmailErrorMsg.setText("Email Addresses should be different");
                altEmailErr=true;
            }
            else{
                altEmailErr=false;
            }
        }
        
        if(altEmailErr){
            jlpAltEmail.setBorder(BorderFactory.createLineBorder(Color.red,1,true));
            lblAltEmailError.setIcon(wrong);
            jlpAltEmail.setBackground(new Color(255,255,204));
            tfAltEmail.setBackground(new Color(255,255,204));
        }
        
        else{
            jlpAltEmail.setBorder(BorderFactory.createLineBorder(new Color(153,153,153),1,true));
            lblAltEmailError.setIcon(right);
            tfAltEmail.setToolTipText(null);
            jlpAltEmail.setBackground(new Color(255,255,255));
            tfAltEmail.setBackground(new Color(255,255,255));
            lblAltEmailErrorMsg.setForeground(Color.white);
        }
    }//GEN-LAST:event_tfAltEmailFocusLost

    private void tfEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfEmailFocusLost
        // TODO add your handling code here:
        //tfEmail.setToolTipText(null);
        
        boolean res;
       if(tfEmail.getText().length()==0){
            tfEmail.setText(emailInitVal);
        }
        
        if(tfEmail.getText().length()==0 || tfEmail.getText().equals(emailInitVal)){
            tfEmail.setToolTipText("Enter your Email");
            emailErr=true;
            
        }
        else{
            res=isValidEmailAddress(tfEmail.getText());
            if(!res){
                emailErr=true;
                lblEmailErrorMsg.setForeground(Color.red);
                lblEmailErrorMsg.setText("Invalid Email Address");
            }
            else{
                emailErr=false;
            }
        }
        
        if(emailErr){
            jlpEmail.setBorder(BorderFactory.createLineBorder(Color.red,1,true));
            lblEmailError.setIcon(wrong);
            jlpEmail.setBackground(new Color(255,255,204));
            tfEmail.setBackground(new Color(255,255,204));
        }
        
        else{
            jlpEmail.setBorder(BorderFactory.createLineBorder(new Color(153,153,153),1,true));
            lblEmailError.setIcon(right);
            tfEmail.setToolTipText(null);
            jlpEmail.setBackground(new Color(255,255,255));
            tfEmail.setBackground(new Color(255,255,255));
            lblEmailErrorMsg.setForeground(Color.white);
        }
    }//GEN-LAST:event_tfEmailFocusLost

    public static boolean isValidEmailAddress(String email) {
        boolean result = true;
        try {
            InternetAddress emailAddr = new InternetAddress(email);
            emailAddr.validate();
        } catch (AddressException ex) {
            result = false;
        }
        return result;
    }
    
    public class NumberDocumentFilter extends DocumentFilter{
        public void insert(DocumentFilter.FilterBypass fp,int off,String string,AttributeSet attr) throws BadLocationException{
            int len=string.length();
            boolean isValidNum=true;
            
            for(int i=0;i<len;i++){
                if(!(Character.isDigit(string.charAt(i)))){
                    isValidNum=false;
                    break;
                }    
            }
            if(isValidNum){
                super.insertString(fp, off, string, attr);
                //fp.insertString(off,string.replaceAll("\\d",""),as);
            }
            else{
                Toolkit.getDefaultToolkit().beep();
            }  
        }
        
        public void replace(DocumentFilter.FilterBypass fp,int off,int length,String string,AttributeSet attr) throws BadLocationException{
            int len=string.length();
            boolean isValidNum=true;
            
            for(int i=0;i<len;i++){
                if(!(Character.isDigit(string.charAt(i)))){
                    isValidNum=false;
                    break;
                }
            }
            if(isValidNum){
                super.insertString(fp, off, string, attr);
                //fp.insertString(off,string.replaceAll("\\d",""),as);
            }
            else{
                Toolkit.getDefaultToolkit().beep();
            }  
        }
        
    }
    
    public class CharDocumentFilter extends DocumentFilter{
        public void insert(DocumentFilter.FilterBypass fp,int off,String string,AttributeSet attr) throws BadLocationException{
            int len=string.length();
            boolean isValidChar=true;
            
            for(int i=0;i<len;i++){
                if(!( Character.isWhitespace(string.charAt(i)) || ((int)string.charAt(i))==39 || Character.isLetter(string.charAt(i)))){
                    isValidChar=false;
                    break;
                }    
            }
            if(isValidChar){
                super.insertString(fp, off, string, attr);
                //fp.insertString(off,string.replaceAll("\\d",""),as);
            }
            else{
                Toolkit.getDefaultToolkit().beep();
            }  
        }
        
        public void replace(DocumentFilter.FilterBypass fp,int off,int length,String string,AttributeSet attr) throws BadLocationException{
            int len=string.length();
            boolean isValidChar=true;
            
            for(int i=0;i<len;i++){
                if(!(Character.isWhitespace(string.charAt(i)) || ((int)string.charAt(i))==39 || Character.isLetter(string.charAt(i)))){
                    isValidChar=false;
                    break;
                }
            }
            if(isValidChar){
                super.insertString(fp, off, string, attr);
                //fp.insertString(off,string.replaceAll("\\d",""),as);
            }
            else{
                Toolkit.getDefaultToolkit().beep();
            }  
        }
        
    }
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAPrevious;
    private javax.swing.JButton btnCNext;
    private javax.swing.JButton btnCPrevious;
    private javax.swing.JButton btnPNext;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLayeredPane jlpAddress;
    private javax.swing.JLayeredPane jlpAltEmail;
    private javax.swing.JLayeredPane jlpConfirmPassword;
    private javax.swing.JLayeredPane jlpContactNo;
    private javax.swing.JLayeredPane jlpEmail;
    private javax.swing.JLayeredPane jlpFName;
    private javax.swing.JLayeredPane jlpLName;
    private javax.swing.JLayeredPane jlpLogo;
    private javax.swing.JLayeredPane jlpPassword;
    private javax.swing.JLayeredPane jlpProgress;
    private javax.swing.JLayeredPane jlpUserName;
    private javax.swing.JSeparator jsp1to2;
    private javax.swing.JSeparator jsp2to3;
    private javax.swing.JScrollPane jspAddress;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lblAccountSetup;
    private javax.swing.JLabel lblAddressError;
    private javax.swing.JLabel lblAltEmailError;
    private javax.swing.JLabel lblAltEmailErrorMsg;
    private javax.swing.JLabel lblCnfPasswordError;
    private javax.swing.JLabel lblCnfPasswordErrorMsg;
    private javax.swing.JLabel lblContactDetails;
    private javax.swing.JLabel lblContactError;
    private javax.swing.JLabel lblEmailError;
    private javax.swing.JLabel lblEmailErrorMsg;
    private javax.swing.JLabel lblFNameError;
    private javax.swing.JLabel lblLNameError;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPasswordError;
    private javax.swing.JLabel lblPasswordErrorMsg;
    private javax.swing.JLabel lblPersonalDetails;
    private javax.swing.JLabel lblUserNameError;
    private javax.swing.JLabel lblUserNameErrorMsg;
    private javax.swing.JPasswordField pfConfirmPassword;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JPanel pnlAccountSetup;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlCardHolder;
    private javax.swing.JPanel pnlContactDetails;
    private javax.swing.JPanel pnlLogo;
    private javax.swing.JPanel pnlPersonalDetails;
    private javax.swing.JPanel pnlProgress;
    private javax.swing.JTextArea taAddress;
    private javax.swing.JTextField tfAltEmail;
    private javax.swing.JTextField tfContactNo;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfFName;
    private javax.swing.JTextField tfLName;
    private javax.swing.JTextField tfUserName;
    // End of variables declaration//GEN-END:variables
}
